### ISSUE TITLE
[Proposal] Initialize collection properties to respect Nullability

### ISSUE THREAD

**Issue by ShortDevelopment** [affederaffe/Tmds.DBus.SourceGenerator#11]
## Issue
Unused collection properties are initialized as `null`.
Therfore the handler code might throw a `NullReferenceException`.

## Solution
Initialize generated collection properties to `Array<T>.Empty()`, `new Dictionary<A, B>()` or `new List<T>()`.

**Comment by affederaffe** [comment]
Yeah, I always wanted to fix this someday, but haven't found the time to do so. Expect this fixed in the next version.

**Comment by affederaffe** [comment]
`null` is now an allowed value and is treated equally to an "empty instance" of the type.

**Comment by affederaffe** [comment]
Completed with the release of 0.016 on NuGet, see https://www.nuget.org/packages/Tmds.DBus.SourceGenerator/0.0.16.
