### ISSUE TITLE
Invalid code generated from mpris dbus interface (duplicate "Introspect" handlers)

### ISSUE THREAD

**Issue by ilya-zlobintsev** [affederaffe/Tmds.DBus.SourceGenerator#12]
I'm trying to generate a handler for these two interfaces:
[org.mpris.MediaPlayer2](https://gitlab.freedesktop.org/mpris/mpris-spec/-/blob/master/spec/org.mpris.MediaPlayer2.xml?ref_type=heads)
[org.mpris.MediaPlayer2.Player](https://gitlab.freedesktop.org/mpris/mpris-spec/-/blob/master/spec/org.mpris.MediaPlayer2.Player.xml?ref_type=heads)

But for both of them, the generated code doesn't compile since it has several switch cases for `Introspect`:
`Tmds.DBus.SourceGenerator.OrgMprisMediaPlayer2Player.g.cs` lines 309-341:
```
                case "org.mpris.MediaPlayer2.Player":
                    switch (context.Request.MemberAsString, context.Request.SignatureAsString)
                    {
                        case ("Introspect", "" or null):
                        {
                            break;
                        }

                        case ("Introspect", "" or null):
                        {
                            break;
                        }

                        case ("Introspect", "" or null):
                        {
                            break;
                        }

                        case ("Introspect", "" or null):
                        {
                            break;
                        }

                        case ("Introspect", "" or null):
                        {
                            break;
                        }

                        case ("Introspect", "" or null):
                        {
                            break;
                        }
```
```
Tmds.DBus.SourceGenerator.DBusSourceGenerator/Tmds.DBus.SourceGenerator.OrgMprisMediaPlayer2Player.g.cs(317,30): error CS8120: The switch case is unreachable. It has already been handled by a previous case or it is impossible to match.
```

**Comment by affederaffe** [comment]
Thank you for the report!
That's indeed a bug where methods with no parameters and no return value where simply ignored.
This should work with https://github.com/affederaffe/Tmds.DBus.SourceGenerator/commit/8854fa8212b20881a020e40e635881d219b648fc, though the CI build currently fails because it depends on a [nightly version of Tmds.DBus.Protocol](https://github.com/tmds/Tmds.DBus?tab=readme-ov-file#ci-packages).
A new version will be released when the Tmds.DBus.Protocol package is uploaded to NuGet.

**Comment by ilya-zlobintsev** [comment]
Thanks, seems to work fine now
