### ISSUE TITLE
[Bug] Methods using handles don't compile

### ISSUE THREAD

**Issue by ShortDevelopment** [affederaffe/Tmds.DBus.SourceGenerator#15]
## Issue
Methods using handles don't compile, as `ReadHandle` is generic and `SafeHandle` is abstract.
```
error CS0411: The type arguments for method 'Reader.ReadHandle<T>()' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```

## Reproduce
`org.bluez.Profile1`
```xml
<?xml version="1.0" encoding="utf-8" ?>
<node>
	<interface name="org.bluez.Profile1">
		<method name="NewConnection">
			<arg type="o" direction="in"/>
			<arg type="h" direction="in"/>
			<arg type="a{sv}" direction="in"/>
			<annotation name="org.qtproject.QtDBus.QtTypeName.In2" value="QVariantMap"/>
		</method>
		<method name="RequestDisconnection">
			<arg type="o" direction="in"/>
		</method>
		<method name="Release">
			<annotation name="org.freedesktop.DBus.Method.NoReply" value="true"/>
		</method>
	</interface>
</node>
```

## Solution
Use `SafeFileHandle`
https://github.com/affederaffe/Tmds.DBus.SourceGenerator/blob/42d16f485453e8182ce9fcf008f9b1844b3bf2f6/Tmds.DBus.SourceGenerator/DBusSourceGenerator.Parsing.cs#L196-L197

https://github.com/affederaffe/Tmds.DBus.SourceGenerator/blob/42d16f485453e8182ce9fcf008f9b1844b3bf2f6/Tmds.DBus.SourceGenerator/DBusSourceGenerator.Utils.cs#L117

**Comment by affederaffe** [comment]
Should be fixed with https://github.com/affederaffe/Tmds.DBus.SourceGenerator/commit/fcef8b51fdf2d20aebf79afb92ed20f6a0cde667.
Do you mind trying the [CI build](https://github.com/affederaffe/Tmds.DBus.SourceGenerator/actions/runs/9391606028) and see if it fixes your issue?

**Comment by ShortDevelopment** [comment]
This fixed it, thanks!
