### ISSUE TITLE
SourceGen'd ValueTuples fails when the target struct has more than 9 members

### ISSUE THREAD

**Issue by jmacato** [affederaffe/Tmds.DBus.SourceGenerator#18]
God knows why these spec writers at FreeDesktop/AT-SPI did this but they have a crazy struct and this sourcegen fails to compensate with it.

```
  <interface name="org.a11y.atspi.Collection">
    <method name="GetMatches">
      <arg direction="in" name="rule" type="(aiia{ss}iaiiasib)"/>
      
```

```
        public static (int[], int, Dictionary<string, string>, int, int[], int, string[], int, bool) ReadStruct_raiiaessiaiiasibz(this ref Reader reader)
        {
            reader.AlignStruct();
            return ValueTuple.Create(reader.ReadArray_ai(), reader.ReadInt32(), reader.ReadDictionary_aess(), reader.ReadInt32(), reader.ReadArray_ai(), reader.ReadInt32(), reader.ReadArray_as(), reader.ReadInt32(), reader.ReadBool());
        }
```

I wonder if it's possible to use a struct instead, though the naming convention for it is something to think about i guess.

**Comment by affederaffe** [comment]
With https://github.com/affederaffe/Tmds.DBus.SourceGenerator/commit/03cdc8820f9e07ae3c9b8039e7cb5f41b951be26, we now let the compiler chunk big tuples (arity > 7) as per C# spec.
Do you mind testing [the CI build](https://github.com/affederaffe/Tmds.DBus.SourceGenerator/actions/runs/9428208981) and see if it fixes the issue?

**Comment by jmacato** [comment]
yep that fixes it, thanks @affederaffe!
