### ISSUE TITLE
Connection property is null despite successful connection

### ISSUE THREAD

**Issue by jmacato** [affederaffe/Tmds.DBus.SourceGenerator#20]
Just noticed on the latest commit that Connection prop is always null. Maybe we missed setting it somewhere?

**Comment by affederaffe** [comment]
For handlers, Connection is an abstract property. Did you implement it correctly?

**Comment by jmacato** [comment]
~~Ahh do i need to manually pass it? Thought IMethodHandler does that for us~~

Yep need to manually pass it, though i wonder if we should make it automatic perhaps?

**Comment by affederaffe** [comment]
I mean you have to pass the Connection instance somewhere, the alternative would be to require it in the constructor.
Though in my opinion, it's better to have it as an abstract property as we very likely need the property in our code anyway.

**Comment by jmacato** [comment]
@affederaffe makes sense, we can consider this issue fixed :pray:
