### ISSUE TITLE
Sourcegen doesnt handle signal-only interfaces properly

### ISSUE THREAD

**Issue by jmacato** [affederaffe/Tmds.DBus.SourceGenerator#21]
So we have the ff: 

```

  <interface name="org.a11y.atspi.Event.Focus">
    <!-- Focus is deprecated in favor of StateChanged with focus passed as its first argument -->
    <signal name="Focus">
      <arg type="s"/>
      <arg type="i"/>
      <arg type="i"/>
      <arg type="v"/>
      <arg name="properties" type="a{sv}"/>
      <annotation name="org.qtproject.QtDBus.QtTypeName.In0" value="QSpiEvent"/>
    </signal>
  </interface>
```
IDE complains about   'OrgA11yAtspiEventFocus' does not implement interface member 'IDBusInterfaceHandler.ReplyInterfaceRequest(MethodContext)' and using the handler without pathhandler would make signals emit fail.

**Comment by affederaffe** [comment]
Fixed with https://github.com/affederaffe/Tmds.DBus.SourceGenerator/commit/c43741664a93405e0ced6d42c9f14fa1b4eb5c81.
