### ISSUE TITLE
INPC for Handlers

### ISSUE THREAD

**Issue by jmacato** [affederaffe/Tmds.DBus.SourceGenerator#22]
Was wondering if it's good to have INPC available for Handler objects so we could properly interface with propchanges notifications

**Comment by affederaffe** [comment]
Would making handler properties abstract work?
For properties where no change notifications are required, one would simply implement an auto-property, not awfully cluttering the code and where desired, the setter may be used.

**Comment by jmacato** [comment]
Yeah i think that would be reasonable enough 🙏

**Comment by affederaffe** [comment]
With https://github.com/affederaffe/Tmds.DBus.SourceGenerator/commit/6c3feb9692c69f4d001bc1cd4036621d939c6b26, every settable property is now abstract so that one can implement a custom setter that one may emit change notifications. Does this work for your use-cases?

**Comment by jmacato** [comment]
Hi @affederaffe Sorry for the late reply, Yes i believe that is quite sufficient for our use case :pray:
