### ISSUE TITLE
Generating proxy and handler of same interface

### ISSUE THREAD

**Issue by uhrm** [affederaffe/Tmds.DBus.SourceGenerator#27]
I'm trying to use the Tmds.DBus.SourceGenerator to write a Linux Bluetooth client application that is using the Bluez advertisement monitoring API. For this use-case, I need proxy access to the `org.freedesktop.DBus.ObjectManager` interface on the Bluez side, and also implement an `org.freedesktop.DBus.ObjectManager` handler interface on my side.

I haven't found a way to accomplish this. Is it possible?

**Comment by affederaffe** [comment]
With https://github.com/affederaffe/Tmds.DBus.SourceGenerator/commit/7afb782ee12993d7a0b1923f50239a572554e985, you should be able to simply declare one AdditionalFiles as Handler and another as proxy.

**Comment by affederaffe** [comment]
The fix in question is included in the new 0.0.20 release.
