### ISSUE TITLE
Class name clash when generating source for ModemManager

### ISSUE THREAD

**Issue by ash-microconnect** [affederaffe/Tmds.DBus.SourceGenerator#28]
The `Bearer` interface of ModemManager includes a `Properties` property. When generating source for this proxy, the automatically generated class that holds the return result of `GetAllPropertiesAsync()` is also called `Properties`, leading to a name clash. To resolve this, could the generated "all properties" class be renamed (`AllProperties` or `GetAllPropertiesResult`?) or perhaps moved outside of the proxy class?

ModemManager XML files: [ModemManager-1.22.0-introspection.zip](https://github.com/user-attachments/files/17124914/ModemManager-1.22.0-introspection.zip)

**Comment by affederaffe** [comment]
f4980bbf0a160e6842a0311b3d86d982bc778855 should address this issue by prepending the interface name to the class identifier. Does this solution work for you?

**Comment by ash-microconnect** [comment]
Sounds perfect. Thanks!
