### ISSUE TITLE
compile-error on handler generation for `Dictionary`

### ISSUE THREAD

**Issue by ShortDevelopment** [affederaffe/Tmds.DBus.SourceGenerator#9]
I'm trying to generate the handler code for the `org.bluez.LEAdvertisement1` interface containing some dictionary properties.

This is a snipped of the generated code trying to access `Key` and `Value` from the `ManufacturerData` dictionary instance:
```cs
case "ManufacturerData":
{
    MessageWriter writer = context.CreateReplyWriter("v");
    writer.WriteDBusVariant(new DBusVariantItem("a{qv}", new DBusDictEntryItem(new DBusUInt16Item(BackingProperties.ManufacturerData.Key), new DBusVariantItem(BackingProperties.ManufacturerData.Value))));
    context.Reply(writer.CreateMessage());
    writer.Dispose();
    break;
}
```

<details>
<summary>Introspection <code>LEAdvertisement1</code></summary>

```xml
<?xml version="1.0" encoding="utf-8" ?>
<node>
	<interface name="org.bluez.LEAdvertisement1">
		<method name="Release"/>
		<property name="Type" type="s" access="read"/>
		<property name="ServiceUUIDs" type="as" access="read"/>
		<property name="ManufacturerData" type="a{qv}" access="read"/>
		<property name="SolicitUUIDs" type="as" access="read"/>
		<property name="ServiceData" type="a{sv}" access="read"/>
		<property name="Includes" type="as" access="read"/>
		<property name="LocalName" type="s" access="read"/>
		<property name="Appearance" type="q" access="read"/>
		<property name="Duration" type="q" access="read"/>
		<property name="Timeout" type="q" access="read"/>
	</interface>
</node>
```

</details>

Btw: Very nice library! ❤️

**Comment by affederaffe** [comment]
Thank you ^^
Do you mind testing with the [latest CI build ](https://github.com/affederaffe/Tmds.DBus.SourceGenerator/actions)?
Seems like I messed up the parsing of dictionaries...

**Comment by ShortDevelopment** [comment]
I tried using v0.0.15 from github artifacts but it produced the same output.

**Comment by affederaffe** [comment]
MSBuild can be pretty aggressive with caching, so perhaps the new version wasn't used.
I bumped the version which should prevent this, I'm sorry to ask again, but please try out this new version.

**Comment by ShortDevelopment** [comment]
It works!

Sorry for keeping you waiting so long, I'm very busy at the moment.
I hadn't realized that `v0.0.15` was also the latest version on Nuget, so msbuild fetched the version from Nuget instead of from my local directory.
